from flask import Flask, request, jsonify
import joblib
import os

app = Flask(__name__)

# Load the model that was generated by train.py
# In Docker, this will be in the /app directory
MODEL_PATH = 'model.pkl'

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Load model only when needed or at startup
        model = joblib.load(MODEL_PATH)
        
        # Get data from POST request
        data = request.get_json()
        
        # Expecting data in a format the model understands (e.g., a list of features)
        prediction = model.predict([data['features']])
        
        return jsonify({'prediction': prediction.tolist()})
    except Exception as e:
        return jsonify({'error': str(e)}), 400

@app.route('/', methods=['GET'])
def home():
    return "California Housing Prediction API is running!"

if __name__ == '__main__':
    # Listen on all interfaces for Docker compatibility
    app.run(host='0.0.0.0', port=5000)